Params:
  Avatar: "static/avatar.jpg"
  Name: "Victoria Cheng"
  Headline: "Building apps that ship & get used | SAIT ‚Äô26 Software Development | Shopify Eng Intern | TypeScript, Python, Go"

  Theme:
    Background: "#1f2937"
    Text: "#ffa375"
    Button: "#60a5fa"
    ButtonText: "#f1f5f9"
    ButtonHover: "#1147bb"
    Link: "#1147bb"
    LinkText: "#f1f5f9"
    LinkHover: "#09265D"

  Socials:
    - Platform: "GitHub"
      Icon: "static/icons/github.svg"
      URL: "https://github.com/victoriacheng15"
    - Platform: "LinkedIn"
      Icon: "static/icons/linkedin.svg"
      URL: "https://linkedin.com/in/victoriacheng15"
    - Platform: "YouTube"
      Icon: "static/icons/youtube.svg"
      URL: "https://www.youtube.com/@victoriacheng15"
    - Platform: "Buy Me a Coffee"
      Icon: "static/icons/buymeacoffee.svg"
      URL: "https://buymeacoffee.com/victoriacheng15"

  Links:
    - Name: "üêß Portfolio Site"
      URL: "https://victoriacheng15.vercel.app/"
    - Name: "Blog"
      URL: "https://victoriacheng15.vercel.app/blog"